spring:
  datasource:
    url: jdbc:mysql://172.60.2.1:3306/uacs?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 30000
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 600000
      pool-name: DataSourceHikariCP
      max-lifetime: 1800000
      connection-test-query: SELECT 1
  redis:
    password: root
    cluster:
      nodes: 172.60.3.1:6379,172.60.3.2:6379,172.60.3.3:6379,172.60.3.4:6379,172.60.3.5:6379,172.60.3.6:6379