spring:
  application:
    name: uacs-web
  profiles:
    active: dev
server:
  port: 20011
  servlet:
    context-path: /uacs
mybatis:
  mapper-locations: classpath:/mapper/*.xml
logging:
  config: classpath:log4j2.xml