spring:
  application:
    name: uacs-web
  profiles:
    active: dev
server:
  port: 20011
  servlet:
    context-path: /uacs
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    use-generated-keys: true
    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  config: classpath:log4j2.xml